# {{APP_NAME}} — AI Coding Instructions

This is a Tauri v2 desktop application with a Rust backend and React 19 + TypeScript frontend.
Generated by [Crabyard](https://crabyard.dev).

---

## Architecture

```
Frontend (React 19 + TypeScript + Vite)
  ↕ IPC bridge via tauri invoke()
Backend (Rust + Tauri v2)
  ↕ Native OS APIs, filesystem, HTTP, persistent storage
```

The frontend runs in a webview. The backend is a native Rust process. Communication happens through Tauri's `invoke()` IPC mechanism — the frontend calls named Rust commands that return serialized results.

---

## Project Structure

```
src/                          # React frontend
├── App.tsx                   # Root component — auth guard + layout
├── main.tsx                  # React entry point
├── index.css                 # Tailwind CSS + theme variables
├── vite-env.d.ts             # Vite + VITE_APP_NAME env type
├── components/
│   ├── DashboardView.tsx     # Main app screen (START HERE for new features)
│   ├── LoginView.tsx         # Auth login UI
│   ├── TitleBar.tsx          # Custom window chrome (macOS/Windows/Linux)
│   ├── UpdateBanner.tsx      # Auto-update notification banner
│   └── ui/                   # UI component primitives (Button, Card, Input, Dialog, ...)
├── hooks/
│   ├── useAuth.ts            # Auth state + login/logout/restore
│   ├── useSettings.ts        # Settings load/save + folder picker
│   └── useUpdater.ts         # App auto-update check/install
├── store/
│   └── appStore.ts           # Zustand global state (auth + settings)
└── lib/
    ├── tauri.ts              # Typed invoke() wrappers for ALL Rust commands
    ├── types.ts              # TypeScript interfaces (mirrors Rust models)
    ├── platform.ts           # OS detection: "macos" | "windows" | "linux"
    └── utils.ts              # cn() — Tailwind class merging helper

src-tauri/                    # Rust backend
├── src/
│   ├── lib.rs                # App init, plugin registration, command handler list
│   ├── main.rs               # Entry point (windows_subsystem = "windows" on release)
│   ├── error.rs              # AppError enum (thiserror) + Serialize for IPC
│   ├── state.rs              # AppState struct — shared mutable state (Mutex)
│   ├── auth/                 # Auth module (token store, validation, flow impl)
│   ├── commands/             # Tauri IPC command handlers
│   │   ├── auth.rs           # login, poll_auth, logout, get_auth_status, restore_auth
│   │   └── settings.rs       # get_settings, set_settings, select_workspace_folder
│   └── models/               # Serde types shared between Rust ↔ TypeScript
│       ├── auth.rs           # AuthStatus, DeviceCodeResponse
│       └── settings.rs       # AppSettings
├── Cargo.toml                # Rust dependencies
├── tauri.conf.json           # Tauri config (window size, bundle, plugins, build commands)
└── capabilities/
    └── default.json          # Permission grants for Tauri plugins
```

---

## How to Add a New Tauri Command

This is the most common extension pattern. Five files need changes:

### 1. Create the Rust handler

Create `src-tauri/src/commands/myfeature.rs`:

```rust
use crate::error::AppResult;
use crate::state::SharedState;
use tauri::State;

#[tauri::command]
pub async fn do_something(
    state: State<'_, SharedState>,
    input: String,
) -> AppResult<String> {
    let _state = state.lock().unwrap();
    Ok(format!("Result: {input}"))
}
```

### 2. Register the module

In `src-tauri/src/commands/mod.rs`, add:

```rust
pub mod myfeature;
```

### 3. Add to the invoke handler

In `src-tauri/src/lib.rs`, add to the `generate_handler![]` macro:

```rust
commands::myfeature::do_something,
```

### 4. Add a typed TypeScript wrapper

In `src/lib/tauri.ts`:

```typescript
export async function doSomething(input: string): Promise<string> {
  return invoke("do_something", { input });
}
```

### 5. Call from React

```typescript
import * as api from "@/lib/tauri";

const result = await api.doSomething("hello");
```

**Naming convention:** Rust uses `snake_case` for commands (`do_something`). Tauri auto-maps to the same name for `invoke()`. TypeScript wrappers use `camelCase` (`doSomething`). Serde model fields use `#[serde(rename_all = "camelCase")]`.

---

## How to Add a New Page/View

1. Create `src/components/MyView.tsx`
2. Add routing logic in `src/App.tsx` (currently uses conditional rendering based on auth state — extend with your own view state or add a router like `react-router-dom`)
3. Use existing UI primitives from `src/components/ui/` (Button, Card, Input, Dialog, etc.)

---

## How to Extend the Zustand Store

In `src/store/appStore.ts`:

```typescript
interface AppState {
  // Add your state fields
  myData: MyType | null;
  setMyData: (data: MyType) => void;
}

export const useAppStore = create<AppState>((set) => ({
  // Add defaults + setters
  myData: null,
  setMyData: (myData) => set({ myData }),
}));
```

Use in components: `const { myData, setMyData } = useAppStore();`

---

## How to Add a New Error Type

In `src-tauri/src/error.rs`, add a variant to `AppError`:

```rust
#[derive(Debug, thiserror::Error)]
pub enum AppError {
    #[error("My custom error: {0}")]
    MyError(String),
    // ... existing variants
}
```

All `AppError` variants are serialized as strings via the `Serialize` impl and sent to the frontend as error messages.

---

## How to Add Shared App State

In `src-tauri/src/state.rs`, add fields to `AppState`:

```rust
pub struct AppState {
    pub my_cache: HashMap<String, String>,
    // ... existing fields
}
```

Access in commands via `State<'_, SharedState>` (which is `Mutex<AppState>`).

---

## How to Add Persistent Settings

1. **Rust model** — add field to `src-tauri/src/models/settings.rs`:
   ```rust
   pub struct AppSettings {
       pub my_setting: Option<String>,
       // ... existing fields
   }
   ```

2. **TypeScript mirror** — add field to `src/lib/types.ts`:
   ```typescript
   export interface AppSettings {
     mySetting: string | null;
     // ... existing fields
   }
   ```

Settings are persisted via `tauri-plugin-store` to a JSON file on disk. The `#[serde(rename_all = "camelCase")]` attribute handles `snake_case` ↔ `camelCase` conversion automatically.

---

## How to Add a Tauri Plugin

1. Add the plugin crate to `src-tauri/Cargo.toml`:
   ```toml
   tauri-plugin-myplugin = "2"
   ```

2. Register in `src-tauri/src/lib.rs`:
   ```rust
   .plugin(tauri_plugin_myplugin::init())
   ```

3. Grant permissions in `src-tauri/capabilities/default.json`:
   ```json
   "permissions": ["myplugin:default"]
   ```

4. Install the JS binding (if the plugin has one):
   ```bash
   bun add @tauri-apps/plugin-myplugin
   ```

---

## UI Components

UI primitives live in `src/components/ui/`. Available components: Button, Card, Input, Dialog, Badge, Separator, Switch, Tooltip, Avatar, ScrollArea, DropdownMenu.

### Adding more shadcn components

```bash
npx shadcn@latest add [component-name]
```

### Adding tesign components

```bash
npx @slideup/design add [component-name]
npx @slideup/design list          # see all available
npx @slideup/design diff          # check for updates
```

### Adding DaisyUI components

DaisyUI components are CSS-class-based. Use Tailwind classes directly:
```tsx
<button className="btn btn-primary">Click me</button>
<div className="card bg-base-100 shadow-xl">...</div>
```

See https://daisyui.com/components/ for the full component reference.

---

## Platform-Specific Code

### Frontend

```typescript
import { getDesktopPlatform } from "@/lib/platform";
const os = getDesktopPlatform(); // "macos" | "windows" | "linux"
```

### Backend (Rust)

```rust
#[cfg(target_os = "macos")]
fn macos_only() { /* ... */ }

#[cfg(target_os = "windows")]
fn windows_only() { /* ... */ }

#[cfg(target_os = "linux")]
fn linux_only() { /* ... */ }
```

### TitleBar

`src/components/TitleBar.tsx` renders platform-native window controls:
- **macOS**: Traffic light buttons (red/yellow/green) on the left
- **Windows**: Minimize/maximize/close on the right
- **Linux**: Standard buttons on the right

Customize the title bar content by editing `TitleBar.tsx`. The window has `decorations: false` in `tauri.conf.json` so the custom title bar replaces the OS chrome.

---

## Environment Variables

- `.env` — local secrets (gitignored, never committed)
- `.env.example` — template with placeholder values (committed)
- `VITE_` prefix — variables accessible in frontend via `import.meta.env.VITE_*`
- Non-prefixed variables — only available in Rust backend via `std::env::var()`
- `vite-env.d.ts` — TypeScript declarations for `ImportMetaEnv`

---

## Build & Dev Commands

```bash
# Development (launches both Vite dev server + Rust backend)
bun run tauri dev

# Production build (creates platform-specific installer)
bun tauri build

# Frontend only
bun run dev          # Vite dev server
bun run build        # tsc + vite build

# Rust only
cd src-tauri
cargo build          # debug build
cargo build --release
cargo test
cargo check          # type-check without building
```

### Build outputs (`src-tauri/target/release/bundle/`)

| Platform | Output |
|----------|--------|
| Windows  | `.msi` installer, `.exe` |
| macOS    | `.dmg` disk image, `.app` bundle |
| Linux    | `.AppImage`, `.deb` package |

---

## Code Conventions

- **Rust errors**: Use `thiserror` derive macro. All errors implement `Serialize` for IPC.
- **Rust serialization**: `serde` with `#[serde(rename_all = "camelCase")]` on all models.
- **TypeScript types**: Mirror Rust models in `src/lib/types.ts`. Keep field names in `camelCase`.
- **Invoke wrappers**: Every Rust command gets a typed wrapper in `src/lib/tauri.ts`.
- **State management**: Zustand store in `src/store/appStore.ts`. No Redux.
- **Styling**: Tailwind CSS v4 with `cn()` helper for conditional classes.
- **Imports**: Use `@/` path alias (maps to `src/`).
- **Window management**: Custom title bar — never use browser `window.close()` etc. Use Tauri's `appWindow` API.
- **All Tauri commands**: Must return `AppResult<T>`, never raw `Result`.

---

## Hard Rules — Do NOT

- Use browser `window.close()`, `window.minimize()` — use Tauri's `appWindow` API.
- Use `fetch()` for backend calls — use typed `invoke()` wrappers in `src/lib/tauri.ts`.
- Add Rust commands without a typed TypeScript wrapper in `src/lib/tauri.ts`.
- Skip `#[serde(rename_all = "camelCase")]` on Rust model structs.
- Put secrets in frontend code — use `.env` with non-`VITE_` prefixed vars for backend-only secrets.
- Modify `TitleBar.tsx` window control logic unless explicitly asked — it handles all three platforms.
- Use Redux, MobX, or other state libraries — this project uses Zustand exclusively.
- Import from `node_modules` paths directly — use `@/` alias for all project imports.
- Use `any` type in TypeScript — strict mode is enabled.

---

## AI-Assisted Development

This project includes three AI instruction files that stay in sync:

| File | Tool |
|------|------|
| `CLAUDE.md` | Claude Code (Anthropic) |
| `.cursorrules` | Cursor IDE |
| `.github/copilot-instructions.md` | GitHub Copilot |

---

## Key Dependencies

### Frontend
| Package | Purpose |
|---------|---------|
| `@tauri-apps/api` | Core Tauri IPC (`invoke`, window, event) |
| `@tauri-apps/plugin-*` | Plugin JS bindings (store, dialog, opener, os, updater, process) |
| `react` / `react-dom` | UI framework |
| `zustand` | Global state management |
| `tailwindcss` + `@tailwindcss/vite` | Styling |
| `clsx` + `tailwind-merge` | Class name utilities |
| `lucide-react` | Icon library |
| `vite` | Build tool + dev server |

### Backend (Rust)
| Crate | Purpose |
|-------|---------|
| `tauri` | Desktop app framework |
| `tauri-plugin-store` | Persistent key-value storage |
| `tauri-plugin-dialog` | Native OS dialogs |
| `tauri-plugin-opener` | Open URLs/files in default app |
| `tauri-plugin-os` | OS/platform detection |
| `tauri-plugin-updater` | App auto-updates |
| `tauri-plugin-process` | Process control (restart/exit) |
| `serde` / `serde_json` | Serialization |
| `reqwest` | HTTP client |
| `thiserror` | Error derive macro |
| `tokio` | Async runtime (via Tauri) |
| `dotenvy` | Load `.env` files (dev only) |

---

## Common Patterns

### Calling Rust from React
```typescript
import * as api from "@/lib/tauri";
try {
  const result = await api.myCommand(arg);
} catch (error) {
  // error is the serialized AppError string
  console.error(error);
}
```

### Using the settings hook
```typescript
const { settings, updateSettings, pickFolder } = useSettings();
await updateSettings({ theme: "dark" });
const folder = await pickFolder();
```

### Opening external URLs
```typescript
import { openUrl } from "@tauri-apps/plugin-opener";
await openUrl("https://example.com");
```

### Persistent storage (Rust side)
```rust
use tauri_plugin_store::StoreExt;
let store = app.store("mydata.json").map_err(|e| AppError::Other(e.to_string()))?;
store.set("key", serde_json::json!("value"));
let val = store.get("key");
```
