use std::collections::HashMap;
use std::path::Path;

pub type TokenMap = HashMap<String, String>;

/// Replace all `{{KEY}}` occurrences in `content` with values from `tokens`.
pub fn replace(content: &str, tokens: &TokenMap) -> String {
    let mut result = content.to_string();
    for (key, value) in tokens {
        result = result.replace(&format!("{{{{{}}}}}", key), value);
    }
    result
}

/// Convert a display name to kebab-case slug.
/// "My Desktop App" → "my-desktop-app"
pub fn to_slug(name: &str) -> String {
    name.trim()
        .to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

/// Convert a kebab-case slug to snake_case for use as a Rust identifier.
/// "my-desktop-app" → "my_desktop_app"
pub fn to_snake(slug: &str) -> String {
    slug.replace('-', "_")
}

/// Build a default reverse-DNS bundle ID from a slug.
/// "my-desktop-app" → "com.example.mydesktopapp"
pub fn to_bundle_id(slug: &str) -> String {
    let clean: String = slug.chars().filter(|c| c.is_alphanumeric()).collect();
    format!("com.example.{}", clean.to_lowercase())
}

/// Returns true if the file at this path should be treated as binary
/// (copied as-is, no token replacement).
pub fn is_binary_path(path: &Path) -> bool {
    const BINARY_EXTS: &[&str] = &[
        "png", "ico", "icns", "jpg", "jpeg", "gif", "webp", "bmp", "svg",
        "woff", "woff2", "ttf", "eot", "otf",
        "lock",   // bun.lock, Cargo.lock — regenerated by hooks
        "pdf", "zip", "gz", "tar", "7z",
    ];
    path.extension()
        .and_then(|e| e.to_str())
        .map(|ext| BINARY_EXTS.contains(&ext.to_lowercase().as_str()))
        .unwrap_or(false)
}

/// Returns true if a path component should cause the entire subtree to be skipped.
/// Skips .git/ (VCS internals) but preserves .github/, .gitignore, CLAUDE.md, etc.
pub fn should_skip_path(path: &Path) -> bool {
    path.components().any(|c| {
        let s = c.as_os_str().to_string_lossy();
        matches!(
            s.as_ref(),
            "node_modules" | "target" | ".git" | "dist" | ".cache"
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_slug() {
        assert_eq!(to_slug("My Desktop App"), "my-desktop-app");
        assert_eq!(to_slug("  hello world  "), "hello-world");
        assert_eq!(to_slug("foo_bar-baz"), "foo-bar-baz");
    }

    #[test]
    fn test_to_snake() {
        assert_eq!(to_snake("my-desktop-app"), "my_desktop_app");
    }

    #[test]
    fn test_to_bundle_id() {
        assert_eq!(to_bundle_id("my-desktop-app"), "com.example.mydesktopapp");
    }

    #[test]
    fn test_replace_tokens() {
        let mut tokens = TokenMap::new();
        tokens.insert("APP_NAME".into(), "My App".into());
        tokens.insert("APP_SLUG".into(), "my-app".into());

        let input = r#"name = "{{APP_SLUG}}", title = "{{APP_NAME}}""#;
        let output = replace(input, &tokens);
        assert_eq!(output, r#"name = "my-app", title = "My App""#);
    }

    #[test]
    fn test_is_binary_path() {
        assert!(is_binary_path(Path::new("icon.png")));
        assert!(is_binary_path(Path::new("bun.lock")));
        assert!(!is_binary_path(Path::new("main.rs")));
        assert!(!is_binary_path(Path::new("Cargo.toml")));
    }
}
